add_newline = false
format = "$directory$git_branch$git_status$character"

[directory]
style = "cyan"
truncation_length = 3
truncate_to_repo = false

[git_branch]
format = "[ ($branch)]($style)"
style = "magenta"

[git_status]
style = "magenta"
format = "[$all_status$ahead_behind]($style)"

[character]
success_symbol = "[>](bold green)"
error_symbol = "[>](bold red)"
