[tools]
rust = "stable"
rebar = "latest"
uv = "latest"

bun = "latest"
node = "lts"

crystal = "1.20"
elixir = "1.20"
erlang = "29.0"
go = "1.26"
ruby = "4.0"
zig = "0.16"
gleam = "1.17"
julia = "1.12"
clojure = "1.12"
leiningen = "2.13"
nim = "2.2"
tinygo = "0.41"
odin = "latest"

[settings]

[settings.ruby]
compile = false

[settings.python]
compile = false
