[tools]
rust = "latest"
uv = "latest"

crystal = "1.20"
elixir = "1.20"
erlang = "29.0"
go = "1.26"
node = "26"
python = "3.14"
ruby = "4.0"
zig = "0.16"

[settings]

[settings.ruby]
compile = false

[settings.python]
compile = false
