[tools]
bat = "latest"
"cargo:eza" = "latest"
fd = "latest"
heroku = "latest"
hurl = "latest"
just = "latest"
ripgrep = "latest"
starship = "latest"
xh = "latest"
xxh = "latest"
yazi = "latest"
zellij = "latest"
zls = "latest"
zoxide = "latest"

bun = "latest"
node = "lts"

crystal = "1.21"
go = "1.27"
ruby = "4.0"
rust = "stable"
zig = "0.16"

"gem:foreman" = "latest"
"gem:rubocop" = "latest"
"gem:solargraph" = "latest"
ruff = "latest"
shfmt = "latest"
erlang = "latest"
elixir = "latest"

[settings.ruby]
compile = false
