[tools]
bat = "latest"
delta = "latest"
dust = "latest"
duf = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
hyperfine = "latest"
jq = "latest"
just = "latest"
"cargo:md-tui" = "latest"
neovim = "latest"
"cargo:procs" = "latest"
ripgrep = "latest"
sccache = "latest"
sd = "latest"
shellcheck = "latest"
superfile = "latest"
"cargo:tre" = "latest"
uv = "latest"
yq = "latest"
zoxide = "latest"
