[tools]
choose = "latest"
delta = "latest"
dust = "latest"
duf = "latest"
fzf = "latest"
gh = "latest"
grex = "latest"
hyperfine = "latest"
jaq = "latest"
jj = "latest"
jless = "latest"
"cargo:md-tui" = "latest"
neovim = "latest"
"cargo:procs" = "latest"
qsv = "latest"
sccache = "latest"
sd = "latest"
shellcheck = "latest"
"cargo:syswatch" = "latest"
tmux = "latest"
ty = "latest"
typst = "latest"
uv = "latest"
watchexec = "latest"
yq = "latest"
"ubi:Canop/broot" = "latest"
"ubi:imsnif/bandwhich" = "latest"
"ubi:boyter/scc" = "latest"
"ubi:rbspy/rbspy" = "latest"
"ubi:Julien-cpsn/ATAC" = { version = "latest", exe = "atac" }
