[tools]
bat = "latest"
choose = "latest"
delta = "latest"
dust = "latest"
duf = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
grex = "latest"
hurl = "latest"
hyperfine = "latest"
jaq = "latest"
jj = "latest"
jless = "latest"
just = "latest"
"cargo:md-tui" = "latest"
neovim = "latest"
"cargo:procs" = "latest"
qsv = "latest"
ripgrep = "latest"
sccache = "latest"
sd = "latest"
shellcheck = "latest"
starship = "latest"
typst = "latest"
uv = "latest"
watchexec = "latest"
xh = "latest"
yazi = "latest"
yq = "latest"
zellij = "latest"
zoxide = "latest"
"ubi:Canop/broot" = "latest"
"ubi:imsnif/bandwhich" = "latest"
"ubi:boyter/scc" = "latest"
"ubi:rbspy/rbspy" = "latest"
"ubi:Julien-cpsn/ATAC" = { version = "latest", exe = "atac" }
